### ISSUE TITLE
Support chips with integrated RNG

### ISSUE THREAD

**Issue by jbeaurivage** [ivajloip/rust-lorawan#101]
There are many microcontrollers which don't have an onboard TRNG. On the other hand, some LoRa chips (eg, SX1262) can be used to generate random numbers. It would be nice to leverage that functionality and give the user the option of using either the microcrontroller (if it exists) or the LoRa chip's.

**Comment by lthiery** [comment]
The trait for RngCore already allows the user to shows what implements RngCore. Does that satisfy why you are looking for?

**Comment by jbeaurivage** [comment]
Not quite. Here is the `Device` definition:

```rust
pub struct Device<R, C, T, RNG, const N: usize = 256>
where
    R: radio::PhyRxTx + Timings,
    T: radio::Timer,
    C: CryptoFactory + Default,
    RNG: RngCore,
{
    crypto: PhantomData<C>,
    region: region::Configuration,
    radio: R,
    timer: T,
    rng: RNG,
    session: Option<SessionData>,
    mac: Mac,
    radio_buffer: RadioBuffer<N>,
    datarate: DR,
}
```

In my case the `radio` field is what would implement `RngCore`, so some kind of shared ownership is required, or adjusting the `Device` struct to accomodate both cases, where `radio` provides random numbers, or when an external `rng` is required.

Also, the random numbers are obtained by talking to the chip over SPI. As far as I understand it, when using the `async_device` module, implementing `RngCore` would have to be blocking function calls, correct?
