### ISSUE TITLE
create a simple lora crate here?

### ISSUE THREAD

**Issue by lthiery** [ivajloip/rust-lorawan#122]
There has been previous discussion of how to encourage interoperability with other Rust Lora projects.

I think one thing that might help is if there was a simple crate to define the modulation's characteristics (ie: Bandwidth, CodingRate, and SpreadingFactor). We have it in here already, but perhaps we define a third-standalone crate that device can depend on? That would make it easy for projects to import those enums while avoiding any other cruft.

Potentially, different methods for calculating time-on-air could be included as well. Any thoughts?

**Comment by lulf** [comment]
Agreed having a separate crate for this would be ideal, as I assume this could then be used by lora-phy to avoid all the conversions. And assuming this crate would not change frequently, it's easier to keep API and version compat sane.

**Comment by lthiery** [comment]
Threw up a quick draft: https://github.com/ivajloip/rust-lorawan/pull/123/files

**Comment by lthiery** [comment]
Note that ideally `lora/src/lora_phy.rs` would disappear as the hope would be that lora-phy adopts the lora crate.

**Comment by ivajloip** [comment]
Yes, that makes sense to me as well. Ship it 🙂

**Comment by ceekdee** [comment]
If lora-phy is to adopt this, please consider including all the bandwidths lora-phy supports:

pub enum Bandwidth {
    _7KHz,
    _10KHz,
    _15KHz,
    _20KHz,
    _31KHz,
    _41KHz,
    _62KHz,
    _125KHz,
    _250KHz,
    _500KHz,
}

LoRaWAN only uses the last three, but perhaps someone will want to do P2P using one or more of the others.

**Comment by lthiery** [comment]
closed by #123
