### ISSUE TITLE
async_device not exposed in the documentation on docs.rs?

### ISSUE THREAD

**Issue by plaes** [ivajloip/rust-lorawan#141]
Some of the examples (embassy's LoRaWAN examples) utilize imports from `lorawan_device::async_device` (see below) but there is currently no documentation about these on https://docs.rs/lorawan-device/0.11.0/lorawan_device/all.html
```rust
use lorawan_device::async_device::lora_radio::LoRaRadio;
use lorawan_device::async_device::{region, Device, JoinMode};
```

**Comment by lthiery** [comment]
I believe #147 solves this
