### ISSUE TITLE
Payload is wrong after 16 bytes

### ISSUE THREAD

**Issue by lthiery** [ivajloip/rust-lorawan#30]
Somehow bytes after byte 16 appear to be corrupt.

The following FRM payload (hex): `44232700018d2a0020000001e40001a30200000000`

with the session keys:
```
	Newskey: AES128([26, C0, 7D, F9, 16, 69, F7, B2, FD, 67, E5, 6B, 53, E9, 6D, BF])
	Appskey: AES128([3C, 23, 2D, 71, 18, 1C, FE, 34, 6C, E7, 54, 39, 37, 23, F5, 30])
```
Becomes the following base64 PhyPayload: `gCYCAEgAGAACYMbhumG/XnwtUwxnGPPe4CuawEsYOjRtKg==`

When I use [this online decoder resource](https://lorawan-packet-decoder-0ta6puiniaut.runkit.sh/?data=gCYCAEgAGAACYMbhumG%2FXnwtUwxnGPPe4CuawEsYOjRtKg%3D%3D&nwkskey=26C07DF91669F7B2FD67E56B53E96DBF&appskey=3C232D71181CFE346CE754393723F530) to parse it, I get the following response:

```
  FRMPayload = 60C6E1BA61BF5E7C2D530C6718F3DEE02B9AC04B18 (from packet, encrypted)
                        = 44232700018D2A0020000001E40001A33A032FF09B (decrypted)
```

As you can see, after byte 16, it's wrong. The payload does seem to roundtrip properly within the `rust-lorawan` though.

I'll try to find a minute to write a unit test about this today, but I thought I'd log it for now and maybe you know where to look for the fix @ivajloip

**Comment by ivajloip** [comment]
This should be fine now (both for lorawan and lorawan-encoding crates) with v0.6.1.
