### ISSUE TITLE
Make rx1 delay and ack timeout configurable

### ISSUE THREAD

**Issue by lulf** [ivajloip/rust-lorawan#35]
After migrating from The Things Network V2 -> V3 with rust-lorawan, we found that we needed to tune rx1 delay from 1 second to 5 seconds. Currently this value is hardcoded to 1 second in region/constants.rs

We could make this another timings parameter in the Timings trait, as I don't think it has anything to do with regions. But it seems that is a hard needle to pass through. Maybe allow setting this on the Configuration would make sense?

@lthiery @ivajloip Wdyt?

**Comment by lthiery** [comment]
> After migrating from The Things Network V2 -> V3 with rust-lorawan, we found that we needed to tune rx1 delay from 1 second to 5 seconds. Currently this value is hardcoded to 1 second in region/constants.rs

You're real issue is that you're using TTN instead of  Helium :P

I left comments on your PR though #36
