### ISSUE TITLE
Release of lorawan-device and lorawan-encoding

### ISSUE THREAD

**Issue by lulf** [ivajloip/rust-lorawan#66]
Could we create a release to crates.io of lorawan-device and lorawan-encoding? Depending on git revisions prevents releasing crates that depend on these.

I'm happy to do it for lorawan-device since it's never released before (and I can add you both as owners), but I think I'd need to be added as owner on crates.io for lorawan-encoding. 

@ivajloip @lthiery ^^

**Comment by lthiery** [comment]
I'm all for that. Should we try to sync the version numbers though? Makes it easier when a client project is using both at the same time (avoid pulling in two versions of encoding).

**Comment by lulf** [comment]
Agreed, maybe just 0.7.0 for both is a nice candidate? Would be nice to merge #61 first as well (and maybe I'll add support for that in the async device as well).

**Comment by lulf** [comment]
I've added the async downlink confirmation support in #67

**Comment by ivajloip** [comment]
Yes, I think it's about time we release both of them and I agree that having consistent versioning between the two will be beneficial. I am a bit split about the naming - should `lorawan-encoding` be pushed as `lorawan` as it was before ([here](https://crates.io/crates/lorawan), but I don't know if or how that can be done) or should we name it `lorawan-encoding` and just add a link to it in the `lorawan`. I don't think it's possible to add automatic redirection in crate.io. If you have ideas around that, I would really be interested to learn more. :slightly_smiling_face:

**Comment by lulf** [comment]
I think it's fine to keep the lorawan crate name for the codec, and we can use lorawan-device for the device. 

Less hassle for existing users of the crate as well.

**Comment by lthiery** [comment]
I'm on board with maintaining lorawan name for the codec. Seems simple enough that way.

**Comment by ivajloip** [comment]
okay, I tried to add you both to the owners of lorawan crate. I think I was looking into it some time ago and got confused about how `encoding/Cargo.toml` should be modified, so if anyone has a good idea how to do it, please feel free to do so. Otherwise I can take a look at it :slightly_smiling_face:

**Comment by lulf** [comment]
Is it ok to change it back to 'lorawan' in encoding/Cargo.toml?

**Comment by lthiery** [comment]
> Is it ok to change it back to 'lorawan' in encoding/Cargo.toml?

Yea I think that's the way to go

**Comment by lulf** [comment]
I've made a PR for the renaming #69 . It was a bit more work than I thought.

**Comment by ivajloip** [comment]
It looks good to me, thanks a lot for doing this! :slightly_smiling_face:

**Comment by lulf** [comment]
Crates released! I've added you both as owners to the lorawan-device crate
